/** Options for initializing a GitHub Pages starter site. */
export interface InitOptions {
  /** Overwrite existing generated files. */
  force?: boolean;
  /** Page title to render. */
  title?: string;
  /** Accent color as a six-digit hexadecimal value. */
  color?: string;
}

/** Result returned after initializing a PagesMark site. */
export interface InitResult {
  /** Absolute docs directory path. */
  dir: string;
  /** Files written into the docs directory. */
  files: string[];
  /** Final page title. */
  title: string;
  /** Final accent color. */
  color: string;
  /** Existing files that were overwritten. */
  overwritten: string[];
}

/** Result returned when checking a PagesMark docs directory. */
export interface CheckResult {
  /** Whether all required files are present. */
  ok: boolean;
  /** Absolute docs directory path. */
  dir: string;
  /** Required files that are present. */
  present: string[];
  /** Required files that are missing. */
  missing: string[];
}

/** Default navy brand color used by PagesMark. */
export const NAVY: string;

/** Default gold accent color used by PagesMark. */
export const GOLD: string;

/** Default PagesMark SVG logo markup. */
export const LOGO: string;

/** Default stylesheet generated by PagesMark. */
export const STYLES: string;

/** Generate the stylesheet for a PagesMark site. */
export function stylesFor(color?: string): string;

/** Generate the HTML document for a PagesMark site. */
export function htmlFor(name: string): string;

/** Generate PagesMark logo SVG markup with a custom accent color. */
export function logoFor(color?: string): string;

/** Return the absolute paths of files required in a docs directory. */
export function requiredFiles(docsDir: string): string[];

/** Initialize a GitHub Pages starter site under the repository's docs directory. */
export function init(dir?: string, options?: InitOptions): InitResult;

/** Check whether a repository contains all PagesMark starter files. */
export function check(dir?: string): CheckResult;
